version: '3'
services:
  app:
    build: .
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ticket_db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ticket_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: